### ISSUE TITLE
Listar tarefas/compromissos: Como usuário, desejo listar todas as minhas tarefas e compromissos atuais, organizados por data.

### ISSUE THREAD

**Issue by dudinhapds** [dudinhapds/projetofinal#3]
- [x] Deve haver uma opção para listar todas as tarefas/compromissos.
- [x] A lista deve ser organizada de forma cronológica, com tarefas/compromissos futuros primeiro.
- [x] Deve ser possível filtrar a lista por prioridade.

**Comment by Sabrinaseixas** [comment]
Todas as funcionalidades foram implementadas. Nota que as tarefas já são listadas por padrão, sem ser necessário selecionar uma opção listar tarefas. Mesmo assim, existem opções para listar e reordenar a lista de tarefas, que mostram a lista e permitem o usuário editá-la.
