### ISSUE TITLE
Priorização de tarefas/compromissos: Como usuário, desejo atribuir prioridades às tarefas e compromissos para ajudar na organização.

### ISSUE THREAD

**Issue by Sabrinaseixas** [dudinhapds/projetofinal#4]
- [x] Deve ser possível definir uma prioridade (alta, média, baixa) para cada tarefa/compromisso.
- [x] As tarefas/compromissos devem ser exibidas na lista principal com base em sua prioridade.
 - [ ] Deve ser possível reordenar as tarefas/compromissos arrastando e soltando na lista.

**Comment by dudinhapds** [comment]
Não foi implementada a funcionalidade de arrastar. No entanto, é possível editar uma tarefa, e escolher sua nova funcionalidade. Além disso, é possível definir a ordenação como sendo por prioridade, ou seja, as tarefas são agrupadas por prioridade.
